# Versão do Docker Compose
version: '3.8'

# Definimos os serviços (os nossos contentores)
services:
  # O nome do nosso serviço de aplicação
  email-service:
    build: .
    restart: unless-stopped
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - API_KEY=${API_KEY}
      - API_MODEL=${API_MODEL}
      - API_BASE_URL=${API_BASE_URL}
    ports:
      - "8080"
    labels:
      # --- Cria o middleware de CORS ---
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors-headers.headers.accessControlMaxAge=86400"

      # --- Aplica o middleware aos routers corretos gerados pelo Dokploy ---
      - "traefik.http.routers.reminder-emailservice-vmsa3g-9-web.middlewares=cors-headers"
      - "traefik.http.routers.reminder-emailservice-vmsa3g-9-websecure.middlewares=cors-headers"
    networks:
      - dokploy-network

# Definimos as redes que os nossos serviços usarão
networks:
  dokploy-network:
    external: true