# Versão do Docker Compose
version: '3.8'

services:
  email-service:
    build: .
    restart: unless-stopped
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - API_KEY=${API_KEY}
      - API_MODEL=${API_MODEL}
      - API_BASE_URL=${API_BASE_URL}
    ports:
      - "8080"
    labels:
      # --- INSTRUÇÕES GERAIS PARA O TRAEFIK ---
      - "traefik.enable=true"
      # Define a qual porta interna do contêiner o Traefik deve enviar o tráfego.
      - "traefik.http.services.email-service.loadbalancer.server.port=8080"

      # --- MIDDLEWARE DE CORS (continua o mesmo) ---
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors-headers.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors-headers.headers.accessControlMaxAge=86400"

      # --- ROUTER PARA O DOMÍNIO CUSTOMIZADO (HTTPS) ---
      # Define um router chamado 'email-service-secure' para o seu domínio.
      - "traefik.http.routers.email-service-secure.rule=Host(`henrylabz.cloud`)"
      # Diz a este router para usar o ponto de entrada HTTPS (porta 443).
      - "traefik.http.routers.email-service-secure.entrypoints=websecure"
      # Habilita o SSL/TLS e usa o resolvedor de certificados 'letsencrypt'.
      - "traefik.http.routers.email-service-secure.tls.certresolver=letsencrypt"
      # Aplica nosso middleware de CORS a este router.
      - "traefik.http.routers.email-service-secure.middlewares=cors-headers"

      # --- ROUTER PARA REDIRECIONAMENTO DE HTTP PARA HTTPS ---
      # Define um router chamado 'email-service-web' para o seu domínio.
      - "traefik.http.routers.email-service-web.rule=Host(`henrylabz.cloud`)"
      # Diz a este router para usar o ponto de entrada HTTP (porta 80).
      - "traefik.http.routers.email-service-web.entrypoints=web"
      # Aplica um middleware padrão do Dokploy para redirecionar para HTTPS.
      - "traefik.http.routers.email-service-web.middlewares=redirect-to-https@file"

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true