services:
  postgres:
    image: postgres:16
    container_name: email-service-db
    environment:
      POSTGRES_DB: email_service_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: