debug: true
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.kwriifwlsaarftqmwjmo.supabase.co:5432/postgres?sslmode=require}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 2      # Máx. de conexões no pool
      minimum-idle: 1            # Mantém pelo menos 1 conexão pronta
      idle-timeout: 180000        # Fecha conexões ociosas após 30s
      max-lifetime: 600000       # Fecha e recria conexões a cada 10 min
      connection-timeout: 30000  # Tempo máx. esperando uma conexão livre (30s)
      pool-name: HikariPool-Supabase

  cloud:
    aws:
      region:
        static: us-east-1
      stack:
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        template:
          default-queue-name-resolution-strategy: LOOKUP

api:
  key: ${API_KEY:key}
  model: ${API_MODEL:openai/gpt-oss-120b}
  base-url: ${API_BASE_URL:https://router.huggingface.co/v1/chat/completions}

app:
  queues:
    email-reminder: "email-reminder-queue"

server:
  port: 8080
  forward-headers-strategy: NATIVE
