spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/email_service_ms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:email}
    password: ${EMAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES:address}
    username: ${RABBITMQ_USERNAME:username}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: ${RABBITMQ_VHOST:vhost}
    port: ${RABBITMQ_PORT:5672}

api:
  key: ${API_KEY:key}
  model: ${API_MODEL:openai/gpt-oss-120b}
  base-url: ${API_BASE_URL:https://router.huggingface.co/v1/chat/completions}

server:
  port: 8081
