debug: true
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    aws:
      region:
        static: us-east-1
      stack:
        auto: false
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        template:
          default-queue-name-resolution-strategy: LOOKUP

api:
  key: ${API_KEY:key}
  model: ${API_MODEL:openai/gpt-oss-120b}
  base-url: ${API_BASE_URL:https://router.huggingface.co/v1/chat/completions}

app:
  queues:
    email-reminder: "email-reminder-queue"

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
