# Define o nome do workflow.
name: devops

# Define quando o workflow será executado.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define os jobs que serão executados.
jobs:
  build:
    runs-on: ubuntu-latest

    # Define as permissões para o job.
    permissions:
      contents: read
      packages: write

    # Passos para o job de build.
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app.jar
          path: target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-app.jar
      - name: Run tests with Maven
        run: ./mvnw -B test --file pom.xml

  # Opcional: Job para empacotar e publicar a imagem Docker.
  # Este job só roda em push para a branch main e com a tag de versão.
  package:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'tags')

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.ref_name }}